spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/wrm   # L'URL de la base de donnees
    username: postgres     # Le nom d'utilisateur
    password: 0000         # Le mot de passe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create     # Mise a jour automatique de la base de donnees (ou 'none' pour pas de mise a jour)
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Le dialecte PostgreSQL pour Hibernate
